(define *smiley* (load-texture "examples/img/smiley.png"))
(blur 0)
(every-frame
  (rotate -40 x-axis)
  (color (vector 1 1 1))
  (texture *smiley*)
  (draw-plane)
  (texture 0)
  (scale 0.3)

  (translate (vmul 0.5 up))
  (rotate (/ (msecs) 10) up)
  (push)
  (translate (vector 0 1.2 0))
  (color (vector 1 0 0 (+ 0.5 (/ (sin (secs)) 4))))
  (draw-sphere)
  (pop)
  (push)
  (translate (vector -1.2 -0.4 0))
  (color (vector 0 1 0 (+ 0.5 (/ (cos (secs)) 4))))
  (draw-sphere)
  (pop)
  (push)
  (translate (vector 1.2 -0.4 0))
  (color (vector 0 0 1 (+ 0.5 (/ (cos (+ (secs) 3.14)) 4))))
  (draw-sphere)
  (pop)
)
