; a not-so-useful clock which does not display the current time
(define (sweep-hand)
    (push)
    (rotate (* (round (modulo (secs) 60)) 6) z-axis)
    (scale 0.5 0.015 0.015)
    (translate (vector 1 0 0))
    (draw-cube)
    (pop))
(define (minute-hand)
    (push)
    (rotate (* (modulo (secs) 3600) 0.1) z-axis)
    (scale 0.5 0.03 0.03)
    (translate (vector 1 0 0))
    (draw-cube)
    (pop))
(define (hour-hand)
    (push)
    (rotate (* (modulo (secs) (* 12 3600)) (/ 0.1 12)) z-axis)
    (scale 0.25 0.04 0.04)
    (translate (vector 1 0 0))
    (draw-cube)
    (pop))
(define (fat-ticks n c)
    (push)
    (rotate (* (/ n c) 360) z-axis)
    (translate (vector 1 0 0))
    (scale 0.04 0.04 0.04)
    (draw-cube)
    (pop)
    (if (> n 0) (fat-ticks (- n 1) c)))
(define (ticks n c)
    (push)
    (rotate (* (/ n c) 360) z-axis)
    (translate (vector 1 0 0))
    (scale 0.01 0.01 0.01)
    (draw-cube)
    (pop)
    (if (> n 0) (ticks (- n 1) c)))
(every-frame
    (scale 0.5 -0.5 0.5)
    (rotate 15 x-axis)
    (translate (vector 0 -0.1 0))
    ; (draw-grid)
    (color red)
    (ticks 60 60)
    (fat-ticks 12 12)
    (color white)
    (hour-hand)
    (minute-hand)
    (sweep-hand))
