; double helix
(define spheres
  (lambda (n)
    (rotate -30.0 z-axis)
    (translate (vector 0.0 0.0 2.0))
    (push)
        (push)
            (translate (vector -3.0 0.0 0.0))
            (scale 0.5)
            (color red)
            (draw-sphere)
        (pop)
        (color white)
        (draw-line (vector -3.0 0.0 0.0) (vector 3.0 0.0 0.0))
        (push)
            (translate (vector 3.0 0.0 0.0))
            (scale 0.5)
            (draw-sphere)
        (pop)
    (pop)
    (if (> n 0) (spheres (- n 1)))
  )
)
(define every-frame
  (lambda ()
    (scale 0.02)
    (rotate -45.0 x-axis)
    (rotate (* (sin (secs)) 360.0) z-axis)
    (translate (vector 0.0 0.0 (* -10 2.0)))
    (spheres 20)))
