(every-frame
    (rotate -15 x-axis)
    (rotate (modulo (/ (msecs) 120) 360) z-axis)
    (scale (+ 0.8 (/ (sin (secs)) 10)))
    (texture 1) ;; Set the last rendered frame as active texture
    (push)
        (translate x-axis)
        (translate (vector 0 0 0.1))
        (draw-plane)
    (pop)
    (push)
        (translate (vmul -1 x-axis))
        (translate (vector 0 0 0.2))
        (draw-plane)
    (pop)
    (push)
        (translate (vmul -1 y-axis))
        (translate (vector 0 0 0.3))
        (draw-plane)
    (pop)
    (push)
        (translate (vmul 1 y-axis))
        (draw-plane)
    (pop)
    (texture 0) ;; No texture
    (translate up)
    (scale 0.3)
    (rotate (/ (msecs) 10) x-axis)
    (color (hsv (* 20 (secs))))
    (draw-cube)
)
