(define *haskell* (load-texture "examples/img/haskell-logo.png"))
(define *smiley* (load-texture "examples/img/smiley.png"))
(define *mosaic* (load-texture "examples/img/mosaic.png"))

(define (every-frame)
    (rotate (+ -75 (* 1 (cos (secs)))) x-axis)
    (translate (vmul (* 0.15 (sin (secs))) x-axis))
    (translate (vmul (* 0.3 (sin (* (secs) 0.6))) y-axis))
    (scale 0.5)
    (push)
        (translate down)
        (texture)
        (color (hsv (/ (msecs) 20)))
        (draw-plane)
    (pop)
    (push)
        (translate y-axis)
        ;;(texture *smiley*)
        (rotate 90 x-axis)
        (color (hsv (+ (/ (msecs) 20) 180)))
        (draw-plane)
    (pop)
    (push)
        (translate (vector -1 0 0))
        (rotate 90 y-axis)
    ;    (draw-plane)
    (pop)
    (texture)
    (draw-line (list (vector 0 0 0) (vector 0 (crndf) (crndf))))
    (rotate (modulo (/ (msecs) 100) 360) z-axis)
    (scale (+ 0.4 (* 0.05 (cos (secs)))))

    (push)
        (translate up)
        (texture 1)
        (draw-cube)
    (pop))
