(define *v* (load-texture "examples/img/mosaic.png"))


(define (every-frame)
    (rotate -15 x-axis)
    (rotate (modulo (/ (msecs) 120) 360) z-axis)
    (scale (+ 0.4 (/ (sin (secs)) 10)))
    (texture 1)
    (push)
        (translate x-axis)
        (draw-plane)
    (pop)
    (push)
        (translate (vmul -1 x-axis))
        (draw-plane)
    (pop)
    (push)
        (translate (vmul -1 y-axis))
        (draw-plane)
    (pop)
    (push)
        (translate (vmul 1 y-axis))
        (draw-plane)
    (pop)
    (scale 0.2)
    (push)
        (rotate (/ (msecs) 10) x-axis)
        (texture *v*)
        (draw-cube)
    (pop)
)
