(define phi 1.6180339887)
(define golden-ratio
  (lambda (n)
    (scale 0.7 1 1)
    (scale 0.9)
    (push)
        (translate (vector 0 1 0))
        (scale 1 (/ 1 phi) 1)
        (translate (vector 2 -1 0))
        (rotate 90 x-axis)
        (push)
            (scale 0.8 1 1)
            (color (vector (sin n) 0.5 0.5))
            (draw-cube)
        (pop)
        (if (> n 0) (golden-ratio (- n 1)))
    (pop)
    (push)
        (translate (vector 0 -1 0))
        (scale 1 (- 1 (/ 1 phi)) 1)
        (translate (vector 2 1 0))
        (rotate 90 x-axis)
        (push)
            (scale 0.8 1 1)
            (color (vector (sin n) (cos n) 0.5))
            (draw-cube)
        (pop)
        (if (> n 0) (golden-ratio (- n 1)))
    (pop)
  )
)
(define init
  (lambda ()
    (scale 0.2)
    (translate (vector 0 -1.2 0))
    (rotate 90 z-axis)
    (rotate -45 y-axis)
    (rotate (modulo (/ (msecs) 30) 360) x-axis)))
(every-frame
  (lambda ()
    (init)
    (golden-ratio 3)))
