(blur 0.3)

(define (draw-laptop)
    (push)
        (translate down)
        (texture)
        (color (hsv (/ (msecs) 20)))
        (push)
        (scale 1.0 0.8 0.1)
        (draw-cube)
        (pop)
    (pop)
    (push)
        (translate (vector 0 0 0.1))
        (translate y-axis)
        ;;(texture *smiley*)
        (rotate 90 x-axis)
        (color (hsv (+ (/ (msecs) 20) 180)))
        (push)
        (scale 1.0 1.0 0.1)
        (draw-cube)
        (pop)
        (scale 0.9)
        (translate (vector 0 0 0.201))
        (texture 1)
        (draw-plane)
    (pop))

(define (every-frame)
    (rotate (+ -45 (* 1 (cos (secs)))) x-axis)
    (translate (vmul (* 0.15 (sin (secs))) x-axis))
    (translate (vmul (* 0.3 (sin (* (secs) 0.6))) y-axis))
    (scale 0.6)
    (draw-laptop)
    (translate (vector 3 0 0))
    (rotate -10 up)
    (draw-laptop))
