(blur 0.8)
(define *red-tint* (load-shader "red-tint"))
(define *fade* (load-shader "fade"))
(define *smiley* (load-texture "examples/img/smiley.png"))
(define (every-frame)
    (texture 0)
    (color white)
    (shader)
    (push)
        (scale (+ 1.5 (* 0.25 (sin (secs)))))
        (draw-plane)
    (pop)
    (shader *red-tint*) ; '("amt" 0.9))
    (texture)
    (translate (vector 0 0 1))
    (scale 0.25)
    (rotate -45.0 x-axis)
    (rotate (modulo (/ (msecs) 20) 360) z-axis)
    (draw-cube)
    (push)
        (shader *fade*) ;; TODO be able to set uniforms
        (translate (vector (cos (/ (secs) 2.0)) 1 0))
        (draw-sphere)
    (pop)
    )
