(define *curx* 0)
(define *cury* 0)
(define *curitem* 0)
(define *width* 10)
(define *height* 12)
(define *last-emerge* (secs))
(define *field*
  (list
    (list 0 0 0 0 0 0 0 0 0 0)
    (list 0 0 0 0 0 0 0 0 0 0)
    (list 0 0 0 0 0 0 0 0 0 0)
    (list 0 0 0 0 0 0 0 0 0 0)
    (list 0 0 0 0 0 0 0 0 0 0)
    (list 0 0 0 0 0 0 0 0 0 0)
    (list 0 0 0 0 0 0 0 0 0 0)
    (list 0 0 0 0 0 0 0 0 0 0)
    (list 0 0 0 0 0 0 0 0 0 0)
    (list 0 0 0 0 0 0 0 0 0 0)
    (list 0 0 0 0 0 0 0 0 0 0)
    (list 0 0 0 0 0 0 0 0 0 0)))
(define *items*
  (list
      (list
        (list 6 6)
        (list 6 0)
        (list 6 0))
      (list
        (list 4 4)
        (list 4 4))
      (list
        (list 0 5 5)
        (list 5 5 0))
      (list
        (list 2)
        (list 2)
        (list 2)
        (list 2))))
(define (draw-box b)
  (if (> b 0)
      (list (push)
      (scale 0.5)
      (color (hsv (* b 36)))
      (draw-cube)
      (pop))))
(define (draw-line l)
  (push)
  (map (lambda (r) 
    (translate (vector 1 0 0))
    (draw-box r)) (reverse l))
  (pop))
(define (draw-field f)
  (push)
  (map (lambda (l)
    (translate (vector 0 1 0))
    (draw-line l)) f)
  (pop))
(define (draw-falling)
  (let ((x *curx*)
        (y *cury*))
      (push)
      (translate (vector x y 0))
      (draw-field (list-ref *items* *curitem*))
      (pop)
      (push)
      (translate (vector x (floor y) 0))
      (draw-field (list-ref *items* *curitem*))
      (pop)))
;; http://stackoverflow.com/questions/1760406/scheme-how-do-i-modify-an-individual-element-in-a-list
(define (list-set l k obj)
  (cond
    ((or (< k 0) (null? l)) #f)
    ((= k 0) (set-car! l obj))
    (else (append (list (car l)) (list-set (cdr l) (- k 1) obj)))))
(define (field-set! x y type)
  (set! *field* (list-set *field* y (list-set (list-ref *field* y) x type)))
  (display *field*)
  (newline))
(define (manifest-item source x y target)
  (map (lambda (l)
    (translate (vector 0 1 0))
    ) source)
  )
(define (every-frame)
  (field-set! 5 5 8)
  (set! *cury* (- *height* (* 4 (- (secs) *last-emerge*))))
  (if (<= *cury* 0)
    (list
        (manifest-item)
        (set! *last-emerge* (secs))
        (set! *curx* (random (- *width* 3)))
        (set! *curitem* (random (- (length *items*) 1)))
        (set! *cury* *height*)))
  (push)
    (color (vmul 0.2 white))
    (translate (vector 0 0 -0.1))
    (draw-plane)
  (pop)
  (scale 0.15)
  (translate (vector (/ *width* -2) (/ *height* -2) 0))
  (draw-field *field*)
  (draw-falling))
