(define *haskell* (load-texture "examples/img/haskell-logo.png"))
(define *smiley* (load-texture "examples/img/smiley.png"))
(define *mosaic* (load-texture "examples/img/mosaic.png"))

(every-frame
    (rotate -45 x-axis)
    (scale 0.5)
    (push)
        (translate down)
        (texture *mosaic*)
        (draw-plane)
    (pop)
    (rotate (modulo (/ (msecs) 20) 360) z-axis)
    (scale 0.2)
    (push)
        (translate down)
        (texture *smiley*)
        (draw-cube)
    (pop)
    (push)
        (rotate 20 z-axis)
        (translate up)
        (texture *haskell*)
        (draw-cube)
        (rotate 20 z-axis)
        (translate (vmul 2 up))
        (texture)
        (draw-cube)
    (pop))
