(define *haskell* (load-texture "examples/img/haskell-logo.png"))
(define *smiley* (load-texture "examples/img/smiley.png"))
(define *mosaic* (load-texture "examples/img/mosaic.png"))

(define (every-frame)
    (rotate -45 x-axis)
    (push)
        (translate down)
        (texture *mosaic*)
        (draw-plane)
    (pop)
    
    (rotate (modulo (/ (msecs) 20) 360) z-axis)
    (scale 0.2)
    (push)
        (translate down)
        (texture *smiley*)
        (draw-cube)
    (pop)
    (push)
        (translate up)
        (rotate (modulo (/ (msecs) 40) 360) z-axis)
        (texture *haskell*)        
        (draw-cube)
    (pop))
