; shows two grids, one at the initial transformation, the other after 5 translations/rotations
(define (cubes n)
    (push)
        (color gray)
        (scale 0.15 0.15 0.01)
        (draw-cube)
    (pop)
    (rotate (* (sin (secs)) 20) (vector 0 0.5 (cos (* (/ (secs) 10) 10))))
    (translate (vector 0 0 (* (sin (secs)) 0.1)))
    (if (> n 0) (cubes (- n 1))))
(define (every-frame)
    (scale 0.5)
    (rotate -45 x-axis)
    (draw-grid)
    (cubes 5)
    (draw-grid))
